language: node_js

node_js:
    - 10

script:
    - yarn run build

cache:
    directories:
        - "node_modules"
    yarn: true

deploy:
    provider: pages
    skip-cleanup: true
    local_dir: src/.vuepress/dist
    github-token: $GITHUB_TOKEN
    repo: nasermirzaei89/nasermirzaei89.github.io
    keep-history: true
    target-branch: master
    on:
        branch: master
