language: node_js
script:
    - yarn run build
cache:
    directories:
        - "node_modules"
# deploy:
#     provider: pages
#     skip-cleanup: true
#     local_dir: src/.vuepress/dist
#     github-token: $GITHUB_TOKEN
#     repo: nasermirzaei89/nasermirzaei89.github.io
#     keep-history: true
#     target-branch: master
#     on:
#         branch: master