title: Naser Mirzaei
url: "http://nasermirzaei89.net"
logo: "/assets/logo.png"
email: nasermirzaei89@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  About me
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: nasermirzaei89
github_username:  nasermirzaei89

# Where things are
source:          .
destination:     ./_site
collections_dir: .
plugins_dir:     _plugins
layouts_dir:     _layouts
data_dir:        _data
includes_dir:    _includes
collections:
  posts:
    output:   true

# Handling Reading
safe:                 false
include:              [".htaccess"]
exclude:              ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "README.md"]
keep_files:           [".git", ".svn"]
encoding:             "utf-8"
markdown_ext:         "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-youtube

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname
show_dir_listing: false

# Outputting
permalink:     /:categories/:year/:month/:day/:title/
paginate_path: /page:num
timezone:      null

quiet:    false
verbose:  false
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

liquid:
  error_mode: warn

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

# Collections
# ---

feed:
  path: feed.xml

theme: minima

disqus:
    shortname: nasermirzaei89-net
