title: Naser Mirzaei
url: 'http://nasermirzaei89.net'
baseurl: ''
author: Naser Mirzaei
email: nasermirzaei89@gmail.com
twitter:
  username: nasermirzaei89
github:
  username: nasermirzaei89

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      type: 'posts'
      layout: 'post'

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag

feed:
  path: feed.xml

disqus:
  shortname: nasermirzaei89-net

webmaster_verifications:
  google: 'N0-Uhbzok_3jUy0rzsYLnwy31QR9oho9zXQzcOpPQ2s'
  bing: '5CB9E0C8772EAD71543DB4009B38FF57'
  yandex: '7a25c3fb2fa9c6b1'
#  alexa: 1234
