version: '3.0'

services:
  site:
    command: jekyll serve --drafts
    image: jekyll/jekyll
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
